version: "3"
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 800:800
      - 8001:8001 
    volumes:
      - data-nginx:/etc/nginx
    depends_on: 
      - web
    links:
      - web
    networks:
      - webdbnet
  web:
    build: ./web
    volumes:
      # Example of host volume mounted in container
      # - /opt/containers/personal/php:/var/www/html
      # Example of docker volume mounted in container
      - web-data:/var/www
    working_dir: /var/www
    networks:
      - webdbnet
  db:
    # build: ./mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /opt/containers/personal/mysql:/var/lib/mysql
    networks:
      - webdbnet
    
networks:
  webdbnet:

volumes:
  web-data:
  data-nginx:
